variable "name" {
  description = "Name prefix for resources"
  type        = string
}

variable "vpc_id" {
  description = "ID of the VPC"
  type        = string
}


variable "public_subnets" {
  description = "IDs of the public subnets (not used since ALB is always internal)"
  type        = list(string)
  default     = []  # Default to empty list since it's not used
}

# ALB is always internal and in private subnets

variable "private_subnets" {
  description = "IDs of the private subnets"
  type        = list(string)
}

variable "alb_security_group_id" {
  description = "ID of the security group for the ALB"
  type        = string
}

variable "ecs_tasks_security_group_id" {
  description = "ID of the security group for the ECS tasks"
  type        = string
}

# Container image is now generated by the ECR module
variable "dockerfile_path" {
  description = "Path to the directory containing the Dockerfile"
  type        = string
  default     = "container"
}

variable "container_port" {
  description = "Port the container listens on"
  type        = number
  default     = 4000
}

variable "cpu" {
  description = "CPU units for the Fargate task"
  type        = number
  default     = 1024 # 1 vCPU
}

variable "memory" {
  description = "Memory for the Fargate task in MiB"
  type        = number
  default     = 2048 # 2 GB
}

variable "desired_count" {
  description = "Desired number of tasks"
  type        = number
  default     = 1
}

variable "max_capacity" {
  description = "Maximum number of tasks for autoscaling"
  type        = number
  default     = 2
}

variable "log_retention_days" {
  description = "Number of days to retain logs"
  type        = number
  default     = 30
}

variable "database_url" {
  description = "Fully constructed database URL"
  type        = string
}

variable "litellm_master_key" {
  description = "Master key for LiteLLM"
  type        = string
}

variable "litellm_salt_key" {
  description = "Salt key for LiteLLM"
  type        = string
}

# Removed litellm_secrets_arn variable as we're no longer using AWS Secrets Manager

variable "task_execution_role_arn" {
  description = "ARN of the ECS task execution role"
  type        = string
}

variable "task_role_arn" {
  description = "ARN of the ECS task role"
  type        = string
}

variable "container_image_uri" {
  description = "URI of the Docker image in ECR"
  type        = string
}

variable "aws_region" {
  description = "AWS region"
  type        = string
}

variable "tags" {
  description = "Tags to apply to resources"
  type        = map(string)
  default     = {}
}

variable "log_bucket_id" {
  description = "ID of the S3 bucket for ALB access logs"
  type        = string
}

# WAF Web ACL variable removed - using CloudFront with WAF instead

# Authentication Variables removed - using internal ALB with security groups instead

variable "container_health_check_start_period" {
  description = "Grace period for container health checks (seconds)"
  type        = number
  default     = 120
}

variable "container_health_check_path" {
  description = "Path for container health checks"
  type        = string
  default     = "/health/liveliness"
}

variable "autoscaling_cpu_target" {
  description = "Target CPU utilization percentage for autoscaling"
  type        = number
  default     = 70
}

variable "autoscaling_memory_target" {
  description = "Target memory utilization percentage for autoscaling"
  type        = number
  default     = 70
}

# vpc_endpoint_service_id removed - now created in fargate module

variable "vpc_cidr" {
  description = "CIDR block for the VPC"
  type        = string
}

variable "azs" {
  description = "List of availability zones"
  type        = list(string)
}

variable "on_premises_cidr_blocks" {
  description = "List of on-premises CIDR blocks"
  type        = list(string)
  default     = []
}

variable "alb_target_group_arn" {
  description = "ARN of the ALB target group"
  type        = string
}

variable "alb_dns_name" {
  description = "DNS name of the ALB"
  type        = string
}

variable "alb_arn" {
  description = "ARN of the ALB"
  type        = string
}
