# LiteLLM Configuration

# -----------------------------------------------------
# General application settings - Using Environment Variables from ECS Fargate
# -----------------------------------------------------
general_settings:
  store_prompts_in_spend_logs: true
  master_key: os.environ/LITELLM_MASTER_KEY
  salt_key: os.environ/LITELLM_SALT_KEY
  database_url: os.environ/DATABASE_URL
  store_model_in_db: true
  disable_spend_logs: false

# -----------------------------------------------------
# Model Configuration
# -----------------------------------------------------
model_list:
  - model_name: "claude-3-7"
    litellm_params:
      model: "bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0" # Example using Claude 3.7
      aws_region_name: os.environ/AWS_REGION
